/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication21;

/**
 *
 * @author 1075474
 */
public class CalculadoraMaxima extends javax.swing.JFrame {
    /**
     * Creates new form CalculadoraMaxima
     */
    public CalculadoraMaxima() {
        initComponents();
    }
    
   double resultado;
   double ultimoD;
   String ultimoOp;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBG = new javax.swing.JPanel();
        jpCorpo = new javax.swing.JPanel();
        jpTela = new javax.swing.JPanel();
        jbResult = new javax.swing.JLabel();
        jpTeclado = new javax.swing.JPanel();
        jb7 = new javax.swing.JButton();
        jb9 = new javax.swing.JButton();
        jbdivider = new javax.swing.JButton();
        jb8 = new javax.swing.JButton();
        jb4 = new javax.swing.JButton();
        jb5 = new javax.swing.JButton();
        jb6 = new javax.swing.JButton();
        jbtimes = new javax.swing.JButton();
        jb1 = new javax.swing.JButton();
        jb2 = new javax.swing.JButton();
        jb3 = new javax.swing.JButton();
        jbminus = new javax.swing.JButton();
        jb0 = new javax.swing.JButton();
        jbdot = new javax.swing.JButton();
        jbCalc = new javax.swing.JButton();
        jbsum = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jpBG.setBackground(new java.awt.Color(192, 75, 36));

        jpCorpo.setBackground(new java.awt.Color(51, 51, 51));

        jpTela.setBackground(new java.awt.Color(204, 204, 204));

        jbResult.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbResult.setForeground(new java.awt.Color(51, 51, 51));
        jbResult.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jpTelaLayout = new javax.swing.GroupLayout(jpTela);
        jpTela.setLayout(jpTelaLayout);
        jpTelaLayout.setHorizontalGroup(
            jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTelaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jbResult, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpTelaLayout.setVerticalGroup(
            jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbResult, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        jpTeclado.setBackground(new java.awt.Color(153, 153, 153));

        jb7.setBackground(new java.awt.Color(51, 51, 51));
        jb7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jb7.setForeground(new java.awt.Color(255, 255, 255));
        jb7.setText("7");
        jb7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jb7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb7ActionPerformed(evt);
            }
        });

        jb9.setBackground(new java.awt.Color(51, 51, 51));
        jb9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jb9.setForeground(new java.awt.Color(255, 255, 255));
        jb9.setText("9");
        jb9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jb9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb9ActionPerformed(evt);
            }
        });

        jbdivider.setBackground(new java.awt.Color(51, 51, 51));
        jbdivider.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbdivider.setForeground(new java.awt.Color(255, 255, 255));
        jbdivider.setText("/");
        jbdivider.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jb8.setBackground(new java.awt.Color(51, 51, 51));
        jb8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jb8.setForeground(new java.awt.Color(255, 255, 255));
        jb8.setText("8");
        jb8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jb8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb8ActionPerformed(evt);
            }
        });

        jb4.setBackground(new java.awt.Color(51, 51, 51));
        jb4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jb4.setForeground(new java.awt.Color(255, 255, 255));
        jb4.setText("4");
        jb4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb4ActionPerformed(evt);
            }
        });

        jb5.setBackground(new java.awt.Color(51, 51, 51));
        jb5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jb5.setForeground(new java.awt.Color(255, 255, 255));
        jb5.setText("5");
        jb5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb5ActionPerformed(evt);
            }
        });

        jb6.setBackground(new java.awt.Color(51, 51, 51));
        jb6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jb6.setForeground(new java.awt.Color(255, 255, 255));
        jb6.setText("6");
        jb6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb6ActionPerformed(evt);
            }
        });

        jbtimes.setBackground(new java.awt.Color(51, 51, 51));
        jbtimes.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtimes.setForeground(new java.awt.Color(255, 255, 255));
        jbtimes.setText("*");
        jbtimes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtimesActionPerformed(evt);
            }
        });

        jb1.setBackground(new java.awt.Color(51, 51, 51));
        jb1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jb1.setForeground(new java.awt.Color(255, 255, 255));
        jb1.setText("1");
        jb1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb1ActionPerformed(evt);
            }
        });

        jb2.setBackground(new java.awt.Color(51, 51, 51));
        jb2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jb2.setForeground(new java.awt.Color(255, 255, 255));
        jb2.setText("2");
        jb2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb2ActionPerformed(evt);
            }
        });

        jb3.setBackground(new java.awt.Color(51, 51, 51));
        jb3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jb3.setForeground(new java.awt.Color(255, 255, 255));
        jb3.setText("3");
        jb3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb3ActionPerformed(evt);
            }
        });

        jbminus.setBackground(new java.awt.Color(51, 51, 51));
        jbminus.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbminus.setForeground(new java.awt.Color(255, 255, 255));
        jbminus.setText("-");
        jbminus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbminusActionPerformed(evt);
            }
        });

        jb0.setBackground(new java.awt.Color(51, 51, 51));
        jb0.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jb0.setForeground(new java.awt.Color(255, 255, 255));
        jb0.setText("0");
        jb0.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jb0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb0ActionPerformed(evt);
            }
        });

        jbdot.setBackground(new java.awt.Color(51, 51, 51));
        jbdot.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbdot.setForeground(new java.awt.Color(255, 255, 255));
        jbdot.setText(".");
        jbdot.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbCalc.setBackground(new java.awt.Color(51, 51, 51));
        jbCalc.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbCalc.setForeground(new java.awt.Color(255, 255, 255));
        jbCalc.setText("=");
        jbCalc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCalcActionPerformed(evt);
            }
        });

        jbsum.setBackground(new java.awt.Color(51, 51, 51));
        jbsum.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbsum.setForeground(new java.awt.Color(255, 255, 255));
        jbsum.setText("+");
        jbsum.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbsum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpTecladoLayout = new javax.swing.GroupLayout(jpTeclado);
        jpTeclado.setLayout(jpTecladoLayout);
        jpTecladoLayout.setHorizontalGroup(
            jpTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTecladoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpTecladoLayout.createSequentialGroup()
                        .addComponent(jb7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbdivider, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpTecladoLayout.createSequentialGroup()
                        .addComponent(jb4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtimes, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpTecladoLayout.createSequentialGroup()
                        .addComponent(jb1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbminus, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpTecladoLayout.createSequentialGroup()
                        .addComponent(jb0, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbdot, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbsum, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jpTecladoLayout.setVerticalGroup(
            jpTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTecladoLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jpTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbdivider, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb9, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtimes, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbminus, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb0, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbsum, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbdot, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout jpCorpoLayout = new javax.swing.GroupLayout(jpCorpo);
        jpCorpo.setLayout(jpCorpoLayout);
        jpCorpoLayout.setHorizontalGroup(
            jpCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCorpoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jpCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpTeclado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jpCorpoLayout.setVerticalGroup(
            jpCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCorpoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jpTela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpBGLayout = new javax.swing.GroupLayout(jpBG);
        jpBG.setLayout(jpBGLayout);
        jpBGLayout.setHorizontalGroup(
            jpBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBGLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jpCorpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jpBGLayout.setVerticalGroup(
            jpBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBGLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jpCorpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCalcActionPerformed

        if (ultimoOp.equals("+")){
            
            jbsumActionPerformed(evt);
            ultimoD = 0;
        }
        
        if (ultimoOp.equals("-")){
            
            jbminusActionPerformed(evt);
            ultimoD = 0;
        }
        
        if (ultimoOp.equals("*")){
            calcMultiplicacao();
            ultimoD = 0;
        }

        if (ultimoOp.equals("/")){
            jbminusActionPerformed(evt);
        }
        
        jbResult.setText(String.valueOf(resultado));
   
    }//GEN-LAST:event_jbCalcActionPerformed

    private void jb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb1ActionPerformed
        String ultimoResultado = jbResult.getText();
        ultimoResultado += jb1.getText();
        jbResult.setText(ultimoResultado);
        ultimoD = Double.parseDouble(jbResult.getText());
    }//GEN-LAST:event_jb1ActionPerformed

    private void jb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb2ActionPerformed
        String ultimoResultado = jbResult.getText();
        ultimoResultado += jb2.getText();
        jbResult.setText(ultimoResultado);
        ultimoD = Double.parseDouble(jbResult.getText());
    }//GEN-LAST:event_jb2ActionPerformed

    private void jb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb3ActionPerformed
        String ultimoResultado = jbResult.getText();
        ultimoResultado += jb3.getText();
        jbResult.setText(ultimoResultado);
        ultimoD = Double.parseDouble(jbResult.getText());
    }//GEN-LAST:event_jb3ActionPerformed

    private void jb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb6ActionPerformed
        String ultimoResultado = jbResult.getText();
        ultimoResultado += jb6.getText();
        jbResult.setText(ultimoResultado);
        ultimoD = Double.parseDouble(jbResult.getText());
    }//GEN-LAST:event_jb6ActionPerformed

    private void jb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb4ActionPerformed
        String ultimoResultado = jbResult.getText();
        ultimoResultado += jb4.getText();
        jbResult.setText(ultimoResultado);
        ultimoD = Double.parseDouble(jbResult.getText());
    }//GEN-LAST:event_jb4ActionPerformed

    private void jb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb5ActionPerformed
        String ultimoResultado = jbResult.getText();
        ultimoResultado += jb5.getText();
        jbResult.setText(ultimoResultado);
        ultimoD = Double.parseDouble(jbResult.getText());
    }//GEN-LAST:event_jb5ActionPerformed

    private void jb7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb7ActionPerformed
        String ultimoResultado = jbResult.getText();
        ultimoResultado += jb2.getText();
        jbResult.setText(ultimoResultado);
        ultimoD = Double.parseDouble(jbResult.getText());
    }//GEN-LAST:event_jb7ActionPerformed

    private void jb8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb8ActionPerformed
        String ultimoResultado = jbResult.getText();
        ultimoResultado += jb8.getText();
        jbResult.setText(ultimoResultado);
        ultimoD = Double.parseDouble(jbResult.getText());
    }//GEN-LAST:event_jb8ActionPerformed

    private void jb9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb9ActionPerformed
        String ultimoResultado = jbResult.getText();
        ultimoResultado += jb9.getText();
        jbResult.setText(ultimoResultado);
        ultimoD = Double.parseDouble(jbResult.getText());
    }//GEN-LAST:event_jb9ActionPerformed

    private void jb0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb0ActionPerformed
        String ultimoResultado = jbResult.getText();
        ultimoResultado += jb0.getText();
        jbResult.setText(ultimoResultado);
        ultimoD = Double.parseDouble(jbResult.getText());
    }//GEN-LAST:event_jb0ActionPerformed

    private void jbsumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsumActionPerformed

        resultado += ultimoD;   
        System.out.println(resultado);
        jbResult.setText("");
        ultimoOp = "+";
    }//GEN-LAST:event_jbsumActionPerformed

    private void jbminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbminusActionPerformed
        resultado -= ultimoD;
        System.out.println(resultado);
        jbResult.setText("");
        ultimoOp = "-";
    }//GEN-LAST:event_jbminusActionPerformed

    private void jbtimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtimesActionPerformed

        jbResult.setText("");
        ultimoOp = "*";
        
    }//GEN-LAST:event_jbtimesActionPerformed

    private void calcMultiplicacao(){
        if (resultado == 0){
            resultado = ultimoD;
            resultado *= ultimoD;
        } else {
            resultado *= ultimoD;
        }
        
        System.out.println(resultado);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraMaxima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraMaxima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraMaxima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraMaxima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraMaxima().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb0;
    private javax.swing.JButton jb1;
    private javax.swing.JButton jb2;
    private javax.swing.JButton jb3;
    private javax.swing.JButton jb4;
    private javax.swing.JButton jb5;
    private javax.swing.JButton jb6;
    private javax.swing.JButton jb7;
    private javax.swing.JButton jb8;
    private javax.swing.JButton jb9;
    private javax.swing.JButton jbCalc;
    private javax.swing.JLabel jbResult;
    private javax.swing.JButton jbdivider;
    private javax.swing.JButton jbdot;
    private javax.swing.JButton jbminus;
    private javax.swing.JButton jbsum;
    private javax.swing.JButton jbtimes;
    private javax.swing.JPanel jpBG;
    private javax.swing.JPanel jpCorpo;
    private javax.swing.JPanel jpTeclado;
    private javax.swing.JPanel jpTela;
    // End of variables declaration//GEN-END:variables
}
