/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication21;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author 1075474
 */
public class PesoNosPlanetas extends javax.swing.JFrame {

    /**
     * Creates new form PesoNosPlanetas
     */
    public PesoNosPlanetas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JlbTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txfInputPeso = new javax.swing.JTextField();
        bCalcular = new javax.swing.JButton();
        lbTextoPrincipal = new javax.swing.JLabel();
        lbPeso = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbPlanetas = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calculo Peso nos Planetas");
        setBackground(new java.awt.Color(51, 51, 51));
        setMaximumSize(new java.awt.Dimension(590, 392));
        setMinimumSize(new java.awt.Dimension(590, 392));
        setResizable(false);
        getContentPane().setLayout(null);

        JlbTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JlbTitle.setForeground(java.awt.Color.white);
        JlbTitle.setText("CALCULO DE PESOS EM VÁRIOS PLANETAS");
        getContentPane().add(JlbTitle);
        JlbTitle.setBounds(40, 20, 488, 32);

        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Digite seu peso:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 80, 230, 16);

        txfInputPeso.setForeground(null);
        txfInputPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfInputPesoActionPerformed(evt);
            }
        });
        getContentPane().add(txfInputPeso);
        txfInputPeso.setBounds(40, 100, 227, 22);

        bCalcular.setForeground(null);
        bCalcular.setText("Calcular");
        bCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(bCalcular);
        bCalcular.setBounds(220, 150, 130, 50);

        lbTextoPrincipal.setForeground(java.awt.Color.white);
        lbTextoPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTextoPrincipal.setText("     ");
        lbTextoPrincipal.setToolTipText("");
        getContentPane().add(lbTextoPrincipal);
        lbTextoPrincipal.setBounds(140, 240, 288, 16);

        lbPeso.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbPeso.setForeground(java.awt.Color.white);
        lbPeso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPeso.setText("   ");
        getContentPane().add(lbPeso);
        lbPeso.setBounds(150, 250, 270, 64);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Escolha o planeta:");

        cbPlanetas.setForeground(null);
        cbPlanetas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mercúrio", "Vênus", "Terra", "Marte", "Júpiter", "Saturno", "Urano", "Netuno", "Lua" }));
        cbPlanetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPlanetasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(297, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPlanetas, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(cbPlanetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 10, 540, 210);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/planetaimg.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 590, 370);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(110, 230, 100, 100);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCalcularActionPerformed
        try {
            mostrarResultado();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "O campo PESO não pode estar vazio!\nTente novamente.");
        }
    }//GEN-LAST:event_bCalcularActionPerformed

    private void cbPlanetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPlanetasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPlanetasActionPerformed

    private void txfInputPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfInputPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfInputPesoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesoNosPlanetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesoNosPlanetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesoNosPlanetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesoNosPlanetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesoNosPlanetas().setVisible(true);
            }
        });
    }
    
    private double selecionarGravidadePlaneta(String planeta){
        if (planeta.equals("Mercúrio")){
            return 3.6; 
        }
      
        if (planeta.equals("Vênus")){
            return 8.7; 
        }
        
        if (planeta.equals("Terra")){
            return 9.8; 
        }
        
        if (planeta.equals("Marte")){
            return 3.7; 
        }
        
        if (planeta.equals("Júpiter")){
            return 24.79; 
        }
        
        if (planeta.equals("Saturno")){
            return 10.44; 
        }
        
        if (planeta.equals("Urano")){
            return 8.69; 
        }
        
        if (planeta.equals("Netuno")){
            return 11.15; 
        }
        
        if (planeta.equals("Lua")){
            return 1.6; 
        }
        
        return 0.0;
    }
    
    private double calcularPeso(double pesoPessoa, double gravidadePlaneta){
        return ((pesoPessoa/10) * gravidadePlaneta);
    }
    
    private void mostrarResultado(){
        double peso = Double.parseDouble(txfInputPeso.getText());
        
        if (peso > 10000000){
            JOptionPane.showMessageDialog(null, "Uau! Que presado!\nO valor não pode ser superior a 999999.");
            return;
        }
        
        String planetaSelecionado = cbPlanetas.getSelectedItem().toString();
        double gravidadePlaneta = selecionarGravidadePlaneta(planetaSelecionado);
        
        DecimalFormat df = new DecimalFormat("#,###.##");
        
        lbTextoPrincipal.setText("O seu peso " + peso + " no planeta " + planetaSelecionado + " é de: ");
        lbPeso.setText((df.format(calcularPeso(peso, gravidadePlaneta))) + "kg");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlbTitle;
    private javax.swing.JButton bCalcular;
    private javax.swing.JComboBox<String> cbPlanetas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbPeso;
    private javax.swing.JLabel lbTextoPrincipal;
    private javax.swing.JTextField txfInputPeso;
    // End of variables declaration//GEN-END:variables
}
